### PR TITLE
Change logo on Windows installer

### PR DESCRIPTION
**Pull request by EdGraVill**
## Description

Change the logo displayed on the Windows Installer for Particle CLI with the new one

 ## How to Test

 

 1. Build windows installer
 2. Execute it

 **Outcome**

Show the new logo in the Windows installer

 ## Related / Discussions

[https://app.shortcut.com/particle/story/100872/cli-logos-update-on-windows-installer](https://app.shortcut.com/particle/story/100872/cli-logos-update-on-windows-installer)

 ## Completeness

 - [x] PR opened :tada:
 - [x] Testing instructions have been provided
 - [x] Tracking story is up to date (tasks are marked complete, state is "ready for review")
 - [x] Changes adhere to repo [conventions](https://github.com/particle-iot-inc/device-control#conventions)
 - [ ] Development [How-To's](https://github.com/particle-iot-inc/device-control#development) have been provided
 - [ ] Docs have been updated (`npm run docs:build`)
 - [x] Branch is rebased against _target_ (typically `main`)

### CODE REVIEW

**Review by CarlosHdez — COMMENTED** [review]
Do the removed logos replace something?

**Comment by EdGraVill** [comment]
@CarlosHdez this PR is not removing anything. Is just replacing old one with new one. Github viewer is not showing the side by side

**Review by CarlosHdez — APPROVED** [review]
I see, thanks

**Review by busticated — APPROVED** [review]

**Comment by EdGraVill** [comment]
@julsjulsjuls

**Pull request merged**
