### PR TITLE
Change logo on CLI

### PR DESCRIPTION
**Pull request by EdGraVill**
## Description

Remove the ASCII logo representation from the Particle CLI installer

 ## How to Test

 

 1. Go to `particle-cli-wrapper/installer/unix/`
 2. Run `./install-cli`

 **Outcome**

Only display `PARTICLE CLI SETUP...` without any logo

 ## Related / Discussions

[https://app.shortcut.com/particle/story/100871/cli-logo-update-on-linux-unix](https://app.shortcut.com/particle/story/100871/cli-logo-update-on-linux-unix)

 ## Completeness

 - [x] PR opened :tada:
 - [x] Testing instructions have been provided
 - [x] Tracking story is up to date (tasks are marked complete, state is "ready for review")
 - [x] Changes adhere to repo [conventions](https://github.com/particle-iot-inc/device-control#conventions)
 - [ ] Development [How-To's](https://github.com/particle-iot-inc/device-control#development) have been provided
 - [ ] Docs have been updated (`npm run docs:build`)
 - [x] Branch is rebased against _target_ (typically `main`)

### CODE REVIEW

**Comment by busticated** [comment]
@julsjulsjuls any thoughts on this one? i added the original ASCII logo a while back b/c users were misidentifying log output but i don't know how much that helped, really.

**Comment by julsjulsjuls** [comment]
@EdGraVill Basically the ask is to remove the ASCII logo since we have no bandwidth to create a new one, you can see the description in the story: https://app.shortcut.com/particle/story/100220/particle-cli-rebrand-for-spectra

I think we can check if we need it back post-Spectra as part of Delorean to make sure we address the concern you had @busticated .

**Comment by busticated** [comment]
@EdGraVill we still need to remove the existing ASCII logo - you might just re-open this and make that change here so that we have the new logo you created in `git` history at least. grab me if you want to pair 👍

**Comment by EdGraVill** [comment]
@busticated Done. Logo removed and the ASCIIed one will live in the history forever haha

**Review by busticated — APPROVED** [review]

**Comment by EdGraVill** [comment]
@julsjulsjuls

**Pull request merged**
